### ISSUE TITLE
Error during ng serve for new project

### ISSUE THREAD

**Issue by LeanderG** [notiz-dev/ngx-tailwind#9]
Thank you for writiing this schematic. It is very useful.

I set up a new Angular 11 project and added Tailwindcss 2. When running `ng serve` I'm getting this error:

```
Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Object.entries(...).flatMap is not a function
    at flattenColorPalette (/home/leander/workspace/angular-tailwindcss/node_modules/tailwindcss/lib/util/flattenColorPalette.js:8:83)
    at /home/leander/workspace/angular-tailwindcss/node_modules/tailwindcss/lib/plugins/divideColor.js:27:53
    at plugins.forEach.plugin (/home/leander/workspace/angular-tailwindcss/node_modules/tailwindcss/lib/util/processPlugins.js:69:5)
    at Array.forEach (<anonymous>)
    at _default (/home/leander/workspace/angular-tailwindcss/node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
    at /home/leander/workspace/angular-tailwindcss/node_modules/tailwindcss/lib/processTailwindFeatures.js:60:54
    at LazyResult.runOnRoot (/home/leander/workspace/angular-tailwindcss/node_modules/postcss/lib/lazy-result.js:276:16)
    at LazyResult.runAsync (/home/leander/workspace/angular-tailwindcss/node_modules/postcss/lib/lazy-result.js:328:26)

Error: ./src/styles.css (./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/dist/cjs.js??ref--12-2!./node_modules/postcss-loader/dist/cjs.js??ref--17!./src/styles.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
    at /home/leander/workspace/angular-tailwindcss/node_modules/tailwindcss/lib/processTailwindFeatures.js:71:83
    at LazyResult.runOnRoot (/home/leander/workspace/angular-tailwindcss/node_modules/postcss/lib/lazy-result.js:276:16)
    at LazyResult.runAsync (/home/leander/workspace/angular-tailwindcss/node_modules/postcss/lib/lazy-result.js:328:26)
```

Steps to reproduce:
1. `ng new <project-name>`
2. Select CSS format
3. `npm i`
4. `ng add ngx-tailwind --cssFormat css`
5. `ng serve`

Running `ng add ngx-tailwind --tailwindVersion 1.9.5` works fine.

**Comment by marcjulian** [comment]
@LeanderG I tried it out with a new Angular 11 application using CSS and `ng serve` works without any error. Can you create a reproduction repository?

**Comment by LeanderG** [comment]
@marcjulian It's now working for me. I think the issue was that I had node v10 installed. I updated to node v14 and that fixed the issue. Thank you for your quick response.

**Comment by marcjulian** [comment]
@LeanderG no problem.
